// import './lessons/01-TypeScript-基础类型(掌握)'
// import './lessons/02-TypeScript-数组和元祖类型(掌握)'
// import './lessons/03-TypeScript-枚举类型(掌握)'
// import './lessons/04-TypeScript-any和void类型(掌握)'
// import './lessons/05-TypeScript-never和object类型(掌握)'
// import './lessons/06-TypeScript-类型断言(掌握)'
// import './lessons/07-TypeScript-变量申明和解构(掌握)'
// import './lessons/08-TypeScript-接口(掌握)'
// import './lessons/09-TypeScript-可选属性和索引签名(掌握)'
// import './lessons/10-TypeScript-索引签名和只读属性(掌握)'
// import './lessons/11-TypeScript-函数接口和混合接口(掌握)'
// import './lessons/12-TypeScript-接口继承(掌握)'
import './lessons/13-TypeScript-函数(掌握)'
